### PR TITLE
Use $output->diag() to avoid messing up progressive terminal output

### PR DESCRIPTION
**Pull request by leonerd**
Raw prints to `STDERR` tend to break it.

### CODE REVIEW

**Comment by NegativeMjark** [comment]
You should probably fix the other places in the file that talk to STDERR otherwise I will cargocult them again.

**Comment by NegativeMjark** [comment]
$ grep -rn STDERR lib/ tests
    lib/SyTest/Identity/Server.pm:128:      print STDERR "Unexpected request to Identity Service for $path";
    lib/SyTest/Synapse.pm:267:            print STDERR $stderr;
    lib/SyTest/Synapse.pm:337:      print STDERR "Process failed ($exitcode)\n";
    lib/SyTest/Synapse.pm:339:      print STDERR "\e[1;35m[server $self->{port}]\e[m: $_\n"
    lib/SyTest/Synapse.pm:383:            print STDERR "\e[1;35m[server $self->{port}]\e[m: $line\n";
    lib/SyTest/Synapse.pm:412:      print STDERR "\e[1;35m[server $self->{port}]\e[m: $_\n"

FWIW

**Comment by leonerd** [comment]
Some of those fixed. The remaining probably want a bit of extra support in the $output instances, which would put it past the realm of "tiny-fixes" for this branch. ;) I'll neaten those up in a bit

**Comment by NegativeMjark** [comment]
LGTM

**Pull request merged**
