### PR TITLE
Enable replication torturing for synapse worker mode

### PR DESCRIPTION
**Pull request by richvdh**
this helps find race conditions in the worker-mode tests.

### CODE REVIEW

**Comment by richvdh** [comment]
turns out lots of our tests are flakey :/

**Comment by erikjohnston** [comment]
Can't we just add this to the invocation in CI?

**Comment by richvdh** [comment]
I guess so. Would that be preferable?

**Comment by erikjohnston** [comment]
I think so, if for no other reason than it'd be nice to still be able to run the worker tests without torture replication on (as it takes so long)

**Comment by richvdh** [comment]
https://github.com/matrix-org/pipelines/pull/18 then

**Pull request closed without merging**
