### PR TITLE
Remove unnecessary installation of Rust from CI step

### PR DESCRIPTION
**Pull request by erikjohnston**
Follows on from https://github.com/matrix-org/sytest/pull/1287

### CODE REVIEW

**Comment by DMRobertson** [comment]
Err is _this_ meant to fail CI?

(Tempted to just leave it as it is and not ask too many questions)

**Comment by erikjohnston** [comment]
I am *extremely* confused as to wtf is going on now.

**Comment by squahtx** [comment]
The docker build step where we install the rust toolchain only adds 32B to the image(????)
https://hub.docker.com/layers/matrixdotorg/sytest-synapse/focal/images/sha256-2206b265dc62720753ee1dbe43b03002f293455a905ee8e8e2a5cd0fc67c2bae?context=explore

Looks like the install command failed, but the GHA still passed?
https://github.com/matrix-org/sytest/runs/8253226528?check_suite_focus=true#step:6:957

**Comment by erikjohnston** [comment]
Aha, that's annoying. Why on earth did the docker image build not fail :/

**Comment by erikjohnston** [comment]
Hopefully https://github.com/matrix-org/sytest/pull/1290 fixes the docker image

**Comment by DMRobertson** [comment]
> Aha, that's annoying. Why on earth did the docker image build not fail :/

See https://github.com/docker/docker.github.io/blob/master/develop/develop-images/dockerfile_best-practices.md#using-pipes

https://stackoverflow.com/questions/69684133/dl4006-warning-set-the-shell-option-o-pipefail-before-run-with-a-pipe-in-it seems to suggest that a `SHELL` directive can be used to set this globally in the dockerfile.

https://github.com/hadolint/hadolint might be interesting to pick this up?

**Comment by erikjohnston** [comment]
This is now fixed!

**Review by squahtx — APPROVED** [review]
lgtm

**Pull request merged**
