### PR TITLE
Test hs/upload limits

### PR DESCRIPTION
**Pull request by Half-Shot**
Changed branch name to apparently make sytest happy which means this follows on from #456.

### CODE REVIEW

**Comment by Half-Shot** [comment]
Well, I must be doing something wrong because this is now the correct branch name, the ``full_uri`` is correct and I'm fairly certain that path comes back with a config.

**Comment by richvdh** [comment]
@matrixbot retest this please

**Comment by richvdh** [comment]
[this is supposed to be testing matrix-org/synapse#3184]

**Comment by richvdh** [comment]
> Well, I must be doing something wrong because this is now the correct branch name, the full_uri is correct and I'm fairly certain that path comes back with a config.

the reason it didn't pick up your synapse branch is that the synapse branch is on a fork of the repo rather than the matrix.org one.

**Pull request merged**
