### PR TITLE
Mkdir before trying to write to the file

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by leonerd** [comment]
Your commit descriptions suggest adding a mkdir(), which the first patch adds, but the second patch then removes it again. Is this intentional?

**Comment by illicitonion** [comment]
Yes, write_yaml_file pretty much exists to do the mkdir, so I figured using it, rather than repeating its code, was the right thing to do.

**Comment by leonerd** [comment]
Ahright. In that case, LGTM

**Comment by Kegsay** [comment]
Test comment

**Pull request merged**
