### PR TITLE
Fix offline mode

### PR DESCRIPTION
**Pull request by erikjohnston**
We added a new build dependency to Synapse so we have to add it to the docker image.

Hopefully fixes https://github.com/matrix-org/synapse/issues/13740

### CODE REVIEW

**Comment by DMRobertson** [comment]
CI is failing---is that expected? I can't remember if we have to build docker images first to get Sytest to be happy

**Comment by erikjohnston** [comment]
@DMRobertson turns out we weren't installing rust. Have now added it to the docker image, but since that isn't rebuilt for PRs I also added it to the GHA job steps. Not sure if we want to remove that before we land it?

**Comment by DMRobertson** [comment]
> Not sure if we want to remove that before we land it?

I'd be happy with docker-image only or GHA-only, with a mild preference for docker-image so that it doesn't have to get installed on every run. But also happy if you just want to merge as-is

**Comment by erikjohnston** [comment]
I'll merge as is and then rip out the GHA installation in a separate PR, i think

**Pull request merged**
