### PR TITLE
Initialize has_flow

### PR DESCRIPTION
**Pull request by kroeckx**
Signed-off-by: Kurt Roeckx <kurt@roeckx.be>

### CODE REVIEW

**Comment by richvdh** [comment]
Please could you merge `develop`

**Comment by kroeckx** [comment]
I have no idea why there are test suite failures, but it clearly doesn't have anything to do with my change.

**Comment by richvdh** [comment]
> I have no idea why there are test suite failures, but it clearly doesn't have anything to do with my change.

The synapse failure is https://github.com/matrix-org/sytest/issues/1036. The Dendrite fails are... I dunno.

**Review by richvdh — APPROVED** [review]
thanks!

**Comment by richvdh** [comment]
> The Dendrite fails are... I dunno.

(@neilalexander has volunteered to take a look)

**Pull request merged**
