### PR TITLE
Change postgres in docker image to use C collation/ctype.

### PR DESCRIPTION
**Pull request by erikjohnston**
This is what Synapse recommends, so we should test it.

c.f. https://github.com/matrix-org/synapse/pull/6734

### CODE REVIEW

**Comment by erikjohnston** [comment]
Ack. Any reason this can't be done as an automated build on docker hub?

**Comment by richvdh** [comment]
none that I'm aware of.

**Comment by richvdh** [comment]
(it may already be automated somehow, but I don't think so)

**Comment by erikjohnston** [comment]
Looking at it I think its a bit of a PITA as we can't specify different `DEBIAN_VERSION` build arg for different builds.

**Pull request merged**
