### PR TITLE
Fix reference to `unpack_sockaddr_un`

### PR DESCRIPTION
**Pull request by richvdh**
Hopefully, fixes:

```
WARN: Error starting server-0: Undefined subroutine &main::pack_sockaddr_un called at lib/SyTest/Homeserver/Synapse.pm line 1208.
```

### CODE REVIEW

**Comment by richvdh** [comment]
(seems to be a problem introduced by #1165. Unclear why it works for some and not others.)

**Comment by DMRobertson** [comment]
Works for me. With this change I can now run tests with the sytest docker container. For completeness, I was using

```
docker run --rm -v /home/dmr/workspace/synapse:/src:ro -v /home/dmr/workspace/sytest/:/sytest -v /tmp/logs:/logs -e POSTGRES=1 -e WORKERS=1 -e MULTI_POSTGRES=1 matrixdotorg/sytest-synapse:testing --torture-replication 50 -s tests/41end-to-end-keys/08-cross-signing.pl
```

**Review by DMRobertson — APPROVED** [review]
No idea why I'm seeing this but you weren't. Maybe your perl version is different to the perl version in the container I'm using? :shrug:

**Comment by richvdh** [comment]
don't know don't care lalalala :hear_no_evil:

**Pull request merged**
