### PR TITLE
Use the correct variable for frozen dict usage

### PR DESCRIPTION
**Pull request by hawkowl**

### CODE REVIEW

**Comment by richvdh** [comment]
@hawkowl we should not forget about fixing this...

**Comment by richvdh** [comment]
the fail is #4026

**Comment by anoadragon453** [comment]
It looks like we forgot to fix this.

**Comment by richvdh** [comment]
every so often I remember about it, have a little cry, and then carry on with my life.

**Comment by richvdh** [comment]
superceded by #778

**Pull request closed without merging**
