### PR TITLE
Add simple /purge_room admin API test

### PR DESCRIPTION
**Pull request by erikjohnston**
Depends on https://github.com/matrix-org/synapse/pull/6307

### CODE REVIEW

**Comment by erikjohnston** [comment]
That's probably fair, though we probably want to think about what to do about the other tests in the file

**Comment by erikjohnston** [comment]
I guess one thing that this does test is if they work in worker mode?

**Comment by richvdh** [comment]
still kinda think we want to test that in `synapse/tests` rather than here... even if that means doing a bunch of annoying boilerplatey work to get a pair of workers set up in a trial env.

**Comment by richvdh** [comment]
> what to do about the other tests in the file

kill them

kill them all

MWAHAHAHAHAHA

**Pull request closed without merging**
