### PR TITLE
Add sqlite pusher_database to Homeserver Dendrite.pm

### PR DESCRIPTION
**Pull request by danpe**
Added new Pusher Database as part of https://github.com/matrix-org/dendrite/pull/1842 to resolve https://github.com/matrix-org/dendrite/issues/611

### CODE REVIEW

**Review by richvdh — APPROVED** [review]
sorry, I'm not sure how this slipped through the net.

It looks sensible to me, though presumably we shouldn't merge it until https://github.com/matrix-org/dendrite/pull/1842 is ready.

**Comment by danpe** [comment]
Thanks @richvdh, true no need to merge yet as we are refactoring the dendrite implementation :)

**Comment by richvdh** [comment]
@neilalexander I see you did a bunch of work on https://github.com/matrix-org/dendrite/pull/1842. Could you have another quick look at this and check it is still relevant?

**Comment by neilalexander** [comment]
@richvdh This is no longer needed since we refactored the push code to use the existing user API database instead, so will close. Thanks for flagging!

**Pull request closed without merging**
