### PR TITLE
Goodbye, synapse's scripts directory

### PR DESCRIPTION
**Pull request by DMRobertson**
In https://github.com/matrix-org/synapse/pull/12118 I am moving scripts into synapse to make CI config neater and tidier. Update Sytest's glue scripts to no longer require the scripts directory to be present.

### CODE REVIEW

**Comment by clokep** [comment]
Are any of these scripts even used in sytest or was it just for consistency?

**Comment by DMRobertson** [comment]
> Are any of these scripts even used in sytest or was it just for consistency?

I suspect just for consistency. But let's see how the sytest jobs on #12118 fair.

**Review by clokep — APPROVED** [review]

**Comment by DMRobertson** [comment]
Many thanks Patrick!

**Comment by DMRobertson** [comment]
> But let's see how the sytest jobs on [matrix-org/synapse#12118](https://github.com/matrix-org/synapse/pull/12118) fair.

They passed. I'm confident that we don't use the scripts in sytest anywhere and a quick grep shows no evidence to the contrary.

**Pull request merged**
