### PR TITLE
Print sytest sha1 during CI run

### PR DESCRIPTION
**Pull request by anoadragon453**
To address https://riot.im/experimental/#/room/#synapse-dev:matrix.org/$154816555286JknwK:sw1v.org

Prints the commit hash of sytest that we're using for a run.

### CODE REVIEW

**Comment by richvdh** [comment]
Sadly, I don't think this is going to work, because we download a tarball of sytest, rather than checking it out from git. I'm not entirely sure why we do that, tbh.

**Comment by anoadragon453** [comment]
Could simply switch to cloning.

**Comment by richvdh** [comment]
yarp. I think @hawkowl wrote the current impl - she may know if there's an advantage to it.

**Comment by hawkowl** [comment]
we could do a shallow clone so it doesn't take forever, but just downloading a tarball was easier at the time.

**Comment by anoadragon453** [comment]
I change change this PR up post-FOSDEM to do a shallow clone since that seems like the simplest solution.

**Comment by richvdh** [comment]
gonna close this for now.

**Pull request closed without merging**
