### PR TITLE
Use `v1` and `v3` endpoints for `/thirdparty` tests

### PR DESCRIPTION
**Pull request by S7evinK**
Updates the endpoints used when testing `/thirdparty`

### CODE REVIEW

**Review by squahtx — APPROVED** [review]
LGTM, but the synapse tests are failing.

Is this blocked on https://github.com/matrix-org/synapse/issues/11158?

**Comment by S7evinK** [comment]
Yep, this is blocked by that issue.
Keeping `unstable` in Sytest and using the fallback in Dendrite unfortunately results in `Destroying unresponded HTTP request to /appservs/1/_matrix/app/v1/thirdparty/protocol/ymca`

**Comment by clokep** [comment]
I made some more changes, I think pairing this with matrix-org/synapse#15317 will fix the tests.

I also pushed this as a separate branch: https://github.com/matrix-org/sytest/pull/new/clokep/appservice-urls so that the synapse PR picks up these changes via branch matching.

**Comment by clokep** [comment]
See https://github.com/matrix-org/sytest/actions/runs/4545210009 run against the matching branch.

**Review by erikjohnston — APPROVED** [review]

**Pull request merged**
