### PR TITLE
Remove some dead code

### PR DESCRIPTION
**Pull request by richvdh**
pusher, synchrotron, federation_reader and media_repository are all unused

### CODE REVIEW

**Comment by leonerd** [comment]
LGTM.

Doesn't Jenkins chew on these any more? I don't see any results from it.

**Comment by richvdh** [comment]
jenkins was dead last night

@matrixbot: test this please

**Comment by richvdh** [comment]
<sigh>

**Comment by richvdh** [comment]
@matrixbot retest this please

**Pull request merged**
