### PR TITLE
test endpoint for updating backup versions

### PR DESCRIPTION
**Pull request by uhoreg**
companion to https://github.com/matrix-org/synapse/pull/4580

### CODE REVIEW

**Comment by richvdh** [comment]
sigh. Will pick this up and see what's the matter with it.

**Comment by uhoreg** [comment]
I wonder how I forgot to merge this one when I merged the synapse PR :frowning_face: It looks like it's failing on unrelated tests.  Maybe because it has newer tests that are running against an older synapse?

**Comment by richvdh** [comment]
> Maybe because it has newer tests that are running against an older synapse?

Oh, almost certainly this. I've deleted the old (merged) synapse branch and updated this one again. It passes locally at least...

**Comment by richvdh** [comment]
\o/

**Pull request merged**
