### PR TITLE
Install List::MoreUtils::XS

### PR DESCRIPTION
**Pull request by richvdh**

### CODE REVIEW

**Comment by leonerd** [comment]
Ugh :/ More MoreUtils mess. I wonder what we're even using this for by now, and whether it can just be excised...

**Comment by richvdh** [comment]
my investigation into the history of the project does not inspire confidence :/

**Comment by richvdh** [comment]
Looks like it is used for exactly one function call. Will have a go at excising it.

**Comment by leonerd** [comment]
https://github.com/matrix-org/sytest/pull/373

**Comment by richvdh** [comment]
yay that looks better

**Pull request closed without merging**
