### PR TITLE
Drop bionic from docker builds and add focal

### PR DESCRIPTION
**Pull request by H-Shay**
Related to #11552, drops bionic from the docker builds which uses EOL python 3.6 and add focal, which uses python 3.9.

### CODE REVIEW

**Comment by callahad** [comment]
> which uses python 3.9.

I think Focal is actually on 3.8 by default: https://packages.ubuntu.com/focal/python3

**Comment by callahad** [comment]
Curious chicken/egg problem with CI: it wants to pull the images that you're naming in this PR, but since the PR hasn't yet been merged, the images haven't yet been built.

**Comment by callahad** [comment]
I suspect we'll need to somewhat blindly merge, and then submit a dummy follow-up PR to make sure it works.

**Comment by H-Shay** [comment]
well I could do a manual push and build but there is an issue with the `testing` image being built which is causing problems.

**Comment by H-Shay** [comment]
This is now unblocked.

**Comment by DMRobertson** [comment]
> Well I could do a manual push and build but there is an issue with the `testing` image being built which is causing problems: see #1114

I think ops are keen for us to avoid personally publishing artefacts where possible.

**Review by DMRobertson — COMMENTED** [review]
I don't quite understand why CI is now passing. It manages to download the image `docker.io/matrixdotorg/sytest-synapse:focal`, but that shouldn't have been published until this gets merged(?)

**Review by DMRobertson — APPROVED** [review]
Oh, I see: you manually [invoked](https://github.com/matrix-org/sytest/actions/runs/1659721512) the docker workflow on this PR via github's UI.

I can see [here](https://hub.docker.com/r/matrixdotorg/sytest-synapse/tags) that Bionic was pushed at 5:30pm but Focal, Buster and Testing were pushed in a batch at 6:20. I think that, plus green CI is evidence enough that this is working!

**Pull request merged**
