### PR TITLE
Test missing auth_event edge case

### PR DESCRIPTION
**Pull request by richvdh**
This is kindof a test for matrix-org/synapse#3960, though to be honest it's just testing one thing that happens to be affected by that (ie, the thing that tripped me up when I was trying to get something else to work, so I happened to have similar tests I could modify relatively easily).

### CODE REVIEW

**Comment by erikjohnston** [comment]
I'm hesitant to have a sytest that tests that synapse succeeds if the server lies about the auth chain in /state (in particular, its quite tempting to assert that it does return the full auth chain).

Can we not test this by lying in `pdu_ids` instead?

**Comment by richvdh** [comment]
> Can we not test this by lying in pdu_ids instead?

I don't think so. The thing we are trying to test is crappy behaviour when things are missing from the auth chain, not when they are missing from the state.

**Comment by richvdh** [comment]
[I suppose that a python test might be a better way to test this. But that sounds like work.]

**Comment by erikjohnston** [comment]
I'm surprised that we do auth checks against auth_ids tbh. Relatedly, shouldn't this sytest have failed since the fix hadn't been merged when the tests ran?

**Comment by richvdh** [comment]
> I'm surprised that we do auth checks against auth_ids tbh

well, empirically...

> Relatedly, shouldn't this sytest have failed since the fix hadn't been merged when the tests ran?

no, because the branches are named the same, so the tests ran against the relevant branch of synapse.

**Comment by erikjohnston** [comment]
> no, because the branches are named the same, so the tests ran against the relevant branch of synapse.

Oh, I must be thinking of synapse merged CI that doesn't test the right branch?

**Comment by erikjohnston** [comment]
The only alternatives I can think of is to only assert the transaction request succeeds (assuming it got killed in that bug), or sending another event in the same transaction and asserting that gets persisted correctly.

**Comment by richvdh** [comment]
> only assert the transaction request succeeds (assuming it got killed in that bug)

Not sure what you mean: I think that is what we are asserting.

**Comment by erikjohnston** [comment]
We're also asserting that the events get correctly passed through to the client. If a server responds incorrectly to a `/state/` its not unreasonable for the receiving server to stop processing those events imo

**Comment by richvdh** [comment]
ah right. Possibly.

**Pull request merged**
